export default [
  { name: 'Year' },
  { name: 'Champion' },
  { name: 'ChampionRange' },
  { name: 'DamageType' },
  { name: 'CCLevel' },
  { name: 'BurstLevel' },
  { name: 'SustainedLevel' },
  { name: 'TankLevel' },
  { name: 'Goal' },
  { name: 'Strengths' },
  { name: 'Weaknesses' },
  { name: 'Ultimate' },
  { name: 'Mechanic' },
  { name: 'Classes' },
  { name: 'Roles' },
  { name: '_pageName' },
  { name: '_pageTitle' },
  { name: '_pageNamespace' },
  { name: '_pageID' },
  { name: '_ID' },
];
