export default [
  { name: 'Name' },
  { name: 'Skin' },
  { name: 'Champion' },
  { name: 'IsBundleExclusive' },
  { name: 'IsLootExclusive' },
  { name: 'Special' },
  { name: 'ReleaseDate' },
  { name: 'BundleRP' },
  { name: 'BundleRP' },
  { name: 'RP' },
  { name: 'Hex1' },
  { name: 'Hex2' },
  { name: 'UniqueSet' },
  { name: '_pageName' },
  { name: '_pageTitle' },
  { name: '_pageNamespace' },
  { name: '_pageID' },
  { name: '_ID' },
];
